services:
  - name: movu-back
    runtime: node
    type: web_service
    plan: free
    env: node
    build_command: npm install && npm run build
    start_command: npm run start
    env_vars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: ""
        scope: private
      - key: EMAIL_HOST
        value: ""
        scope: private
      - key: EMAIL_PORT
        value: ""
        scope: private
      - key: EMAIL_USER
        value: ""
        scope: private
      - key: EMAIL_PASS
        value: ""
        scope: private
